variables:
  - &image mcr.microsoft.com/dotnet/sdk:8.0-jammy
steps:
  build:
    image: *image
    commands: dotnet build
  test:
    image: *image
    commands: dotnet test --collect:"XPlat Code Coverage"
  pack:
    image: *image
    commands: dotnet pack --version-suffix $CI_PIPELINE_NUMBER
  publish:
    image: *image
    when:
      branch: main
      event: push
    commands: dotnet nuget push -s https://nuget.ellpeck.de/v3/index.json **/*.nupkg -k $BAGET_KEY -n
    secrets:
      - baget_key
